name: Skribos

on:
  push:
    branches: 
      - master
      - 'preview*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get branch name
      run: echo ::set-output name=reference::${GITHUB_REF:11}
      id: branch
    - name: Update Skribos dependencies
      run: docker run --volume "$(pwd):/data" leonidlezner/skribos skribos_update.sh
    - name: Run Skribos for German version
      run: docker run --volume "$(pwd):/data" leonidlezner/skribos skribos_build.sh dist/${{ steps.branch.outputs.reference }} lernos-podcasting-guide-de de-DE
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: dist
        keep_history: true
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
